name: build plugin

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode package
      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Minigames-Core
          path: ./Plugin/target/
  upload_nexus_pkg:
    runs-on: ubuntu-latest
    needs: [ build_plugin ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - uses: whelk-io/maven-settings-xml-action@v4
        with:
          active_profiles: '[ "github" ]'
          servers: '[
              {  "id": "github", "username": "eric2788", "password": "${{ secrets.GITHUB_TOKEN }}" },
              { "id": "nexus-dnmc", "username": "${{ secrets.NEXUS_USER }}", "password": "${{ secrets.NEXUS_PASSWORD }}" }
            ]'
      - name: Publish package
        run: mvn --batch-mode deploy